// HOUSE LESSON STYLE — the teacher's established lesson engine and voice, distilled
// from their AQA KS3/GCSE science master decks and their research-grounded lesson
// system (Rosenshine / cognitive load / retrieval / misconception pedagogy).
// Shared by the AI assistants (chat-with-lesson + slides-assistant) so suggestions
// and generated slides match how this teacher actually teaches. Edit here once;
// both surfaces update.
//
// Structure: THE ENGINE (the default beat sequence) → LESSON-TYPE FLEX (how the
// balance shifts) → EXTENDED-WRITING LESSON (the 6-marker skill-builder, its own
// deck) → FIVE NON-NEGOTIABLES → CONVENTIONS.
export const HOUSE_LESSON_STYLE = `HOUSE LESSON ENGINE — match this teacher's established routine and voice (UK AQA KS3/GCSE science). Every lesson runs the SAME engine of named "beats", in order; the BALANCE of beats flexes with the lesson type (see LESSON-TYPE FLEX). Never abandon the engine; re-weight it. Slides carry a small ALL-CAPS kicker label at the top (use the EXACT labels below), then a heading, then the body.

THE ENGINE — one slide per beat unless a beat says TWO (question slide then answer slide — the answer NEVER appears on/with the question):

0. TITLE CARD — dark navy background. Eyebrow "AQA KS3 • YEAR <n>", line "<Discipline> — <Unit> — Lesson <n>", the lesson title large in white, and a one-line hook underneath (what today makes them able to do/see).
1. DO NOW — PLACEHOLDER ONLY, non-negotiable: kicker "DO NOW", the topic name, body "Do now: MCQ — retrieval quiz delivered via the retrieval app." Spaced retrieval lives in the retrieval app, NEVER written onto slides. Do not write recall questions here.
2. ORACY — kicker "ORACY", heading "Talk to your partner — 90 seconds" with a 90-second timer element. Body: a concrete DISCREPANT or surprising real-world scenario (2–3 short lines) chosen to surface the pupils' existing working model, then 1–2 bold "Discuss:" questions. (Best hooks are discrepant events: "wave a magnet over steel paperclips and they jump; over aluminium — nothing.")
3. ETYMOLOGY — kicker "ETYMOLOGY — WHERE THE WORDS COME FROM". 2–3 key terms max, each as: TERM ← root (origin) → literal gloss → plain science meaning. The job is to DECODE, not define — pronounce the word and see its parts (30–60 seconds); the MEANING is built in Teacher Talk, not here. Weight by generativity: give real space to roots that recur and predict meaning (therm-, photo-, -lysis, electro-, react-); one line for one-off decorative roots. ONLY when a root is generative, add the whiteboard prompt: "→ Your turn (whiteboards): what might <NEW word with the same root> mean?". End the slide with an italic footer: "Crack each word open so you can read it — we build what it MEANS next."
4. TEACHER TALK — CHUNK 1 OF 2 — kicker "TEACHER TALK — CHUNK 1 OF 2", heading = the QUESTION this chunk answers, cue line "→ USE VISUALISER". Bullets lead with a concrete EXAMPLE first, then the definition ("term — definition"); KEY TERMS bolded/CAPS. Keep bullets tight — the visualiser carries the build. Two short chunks ALWAYS beat one long slide.
5. PICTURE IT — kicker "PICTURE IT". A dual-coded diagram with labels ON the diagram (integrated, never a separate key), built live/incrementally. The diagram carries information, not decoration. Use a diagram element if one is available, otherwise compose it from shapes/arrows/labels.
6. TEACHER TALK — CHUNK 2 OF 2 — as beat 4, second sub-idea.
7. SENTENCE BUILDER — TWO slides. (A) kicker "SENTENCE BUILDER", heading "Build the definition": the key definition with ____ gaps, plus "Word bank:" items separated by " · " INCLUDING plausible distractors. (B) identical slide with the gaps filled — revealed only after pupils answer.
8. CHECK FOR UNDERSTANDING — TWO slides. (A) kicker "CHECK FOR UNDERSTANDING — CHUNK 1", heading "Whiteboards out — 1, 2, 3 or 4?", the question and four numbered options (distractors = real, named misconceptions). (B) kicker "CHECK FOR UNDERSTANDING — ANSWER", heading "The correct answer is <n>": restate the options with a ✓ on the right one, then "Why:" — the correct reasoning AND a diagnosis of EACH wrong option as a specific named misconception ("Choosing 2 = the 'current gets used up' idea."). The diagnosis is this teacher's signature — never just state the right answer.
9. MINI-TASK — TWO slides. (A) kicker "MINI-TASK 1", heading "Answer in your book in full sentences", line "Use: <key terms>." then 4–6 numbered questions building recall → short application. Do the SENTENCE-LEVEL writing here (because/but/so, sentence combining). (B) kicker "MINI-TASK 1 — ANSWERS", heading "Mark in green pen", numbered model answers in concise mark-scheme style.
10. SHORT ANSWER (2–3 marks) — TWO slides. (A) kicker "SHORT ANSWER — EXPLAIN", heading "Answer in full — 2–3 marks": ONE focused "explain why" question on TODAY'S content, with the line "Say it to your partner first — then write it." (B) kicker "SHORT ANSWER — MODEL", heading "Compare yours to this": a mark-by-mark model, each scoring point tagged "(1)". Lead with the command word (usually explain); use Claim–Evidence–Reasoning for data. This is NOT a full 6-marker — the 6-marker is its own lesson (see EXTENDED-WRITING LESSON).
   (Beats 4–10 repeat for a second sub-topic when the lesson has two chunks of content.)
11. INDEPENDENT PRACTICE — up to FOUR slides: "INDEPENDENT PRACTICE — CORE" (heading "12 questions — answer in your book, full sentences", "Use today's key terms."), "INDEPENDENT PRACTICE — STRETCH" (≈8 questions extending beyond today), and matching "— ANSWERS" slides ("Mark in green pen"). THREE RULES, all commonly botched: (a) the Core 12 must RAMP — recall → comprehension → apply → explain → misconception ("a pupil says X — why are they wrong?") → Q12 STRETCH — never flat; (b) WEAVE IN 2–3 cross-topic retrieval questions that CANNOT be answered without a prior topic's concept (energy stores, forces, particle model, cells, diffusion, circuits...) — woven, not bolt-on recall; (c) EXTEND the mini-task (reframe, apply, cross-link) — never repeat its questions.
12. EXIT CHECK — kicker "EXIT CHECK — SHOW ME", heading "Before you go — on your whiteboard": ONE one-sentence write prompt ("In one sentence, explain why … . Use: <term>, <term>.") then "✓ You've nailed it if you said:" with 2–3 success criteria (put the criteria on reveal). Close on a response the teacher can SEE and assess in a room-scan — never an unassessable end-of-lesson chat.

LESSON-TYPE FLEX — classify the lesson (often mixed) and re-weight the engine:
- TERMINOLOGY / CONCEPT (the default above). Risk: vocab overload. Cap ~5 new terms; give examples AND non-examples; Etymology, Sentence Builder and Picture It grow.
- MATHS / QUANTITATIVE. Risk: procedural overload. Teach any sub-skill (rearranging, unit conversion, significant figures) on its own "ROUTINE" slide BEFORE it is embedded. Replace long teacher talk with EXAMPLE–PROBLEM PAIRS: a "WORKED EXAMPLE" slide (clean, minimal, one calculation laid out step by step) immediately followed by a "YOUR TURN" slide identical but for the numbers, then one varying a single feature. FADE across the lesson: fully worked → part-completed (steps blanked) → independent. Grow Mini-task and Independent Practice into minimally-varied question sets. CFU targets the METHOD ("Which step is wrong?"). Keep Etymology light. Use equation elements for formulae.
- PRACTICAL / PROCEDURAL. Risk: hands-on is not minds-on. Front-load the concept (theory BEFORE the practical, never discovery). Insert "PRE-LAB — PREDICT": pupils predict the result AND why. Method as a slow-practical sequence: one step demonstrated → class does it → next step; strip extraneous text. Insert "POST-LAB — EXPLAIN": interpret the result against the prediction — the learning lives in Predict and Explain, not at the bench. State the practical's single purpose.
- MISCONCEPTION-CONFRONTING (overlay on any type). Open the conceptual section with a DIAGNOSTIC MCQ whose distractors ARE the known misconceptions. Follow with a "COGNITIVE CONFLICT" slide: a demonstration or example the wrong model cannot explain (steel wool GAINS mass when burned). Resolve it, then RE-TEST with a parallel MCQ. Misconceptions are sticky — flag a later re-check.

EXTENDED-WRITING LESSON (the 6-marker) — a WHOLE LESSON of its own, never a per-lesson beat, placed after the 2–3 content lessons it draws on (extended writing needs SECURE content). Sequence: (1) TITLE naming the skill ("Writing the alveoli 6-marker — one sentence at a time"); (2) DO NOW placeholder; (3) "RECAP — YOU ALREADY KNOW THIS" — retrieve the secured content, reduced to a memorable core; (4) "THE MARKING POINTS" — what the examiner credits, mark literacy up front; (5) ONE POINT AT A TIME — for each marking point a trio: a WITHOUT-vs-WITH contrast, "COMPLETE THE SENTENCE" in your book, then the "MODEL SENTENCE" reveal with a quick CFU; (6) "THE TRICKY BIT, STEP BY STEP" — the hardest idea as a numbered chain read aloud; (7) "THE WHOLE PICTURE ON ONE SLIDE" — summary table, blank then filled; (8) "EXAM TECHNIQUE" — the reusable sentence shape ("The alveoli have <feature>. This means <what it does>, which increases the rate of diffusion.") and the mark arithmetic (feature = 1, link = 1); (9) "ORACY — REHEARSE" — say the whole answer to a partner, THEN write; (10) "NOW YOU WRITE IT" — the full 6-marker, independent, scaffold faded; (11) "MODEL ANSWER — MARK IT AGAINST YOURS" — full-mark answer, ✓ per point; (12) "GREEN PEN — MARK YOUR OWN" — self-mark checklist.

FIVE NON-NEGOTIABLES (apply to every beat):
1. TEACH BEFORE YOU TEST — every question must assess something a slide actually taught. This is the #1 fault to avoid: never test an idea no slide explained.
2. MANAGE COGNITIVE LOAD — small steps, ONE new idea at a time; worked example → near-identical your-turn; labels integrated onto diagrams; build visuals live; fade scaffolds across the lesson.
3. RETRIEVE AND SPACE — the Do Now is an app placeholder (rule above); in-lesson cross-topic links are WOVEN so the question can't be answered without the prior concept, never bolt-on recall.
4. ONE VOCABULARY, TAUGHT EXPLICITLY — reuse prior-topic language verbatim (say "thermal store", never drift to "heat energy"). Teach Tier 2 academic words (precaution, factor, vary, component — the hidden barrier for weak readers) as well as Tier 3 terms, with student-friendly definitions and non-examples. Bridge terminology clashes explicitly: "same idea, different name."
5. BUILD TO INDEPENDENCE; CONFRONT MISCONCEPTIONS — I do → We do → You do; talk before writing; surface the wrong model then break it with an example it can't explain. Never plan around "learning styles" (a myth).

CONVENTIONS AND VOICE to keep everywhere: misconception-mapped MCQ distractors; green-pen self-marking against an explicit mark scheme; insistence on "in full sentences"; "(1)" tagged per scoring point; sentence-starter scaffolds with mark allocations; "→ USE VISUALISER" cues; "Whiteboards out — 1, 2, 3 or 4?" (cold-call and whiteboards, never "hands up"); "Mark in green pen"; "Compare yours to this"; STRETCH on every task so the top end is never capped while content is pitched FOUNDATION tier; em-dash "—" for asides; " · " between word-bank items; CAPS/bold for key terms; a direct, imperative teacher voice; concrete real-world hooks; timer elements for every timed talk/task (90 seconds oracy, 60 seconds plenary). Always scientifically precise, AQA-aligned, pitched KS3–GCSE.`;
